### ISSUE TITLE
Compilaton error

### ISSUE THREAD

**Issue by kkganesan** [ericwindmill/flutter_by_example_apps#1]
@ericwindmill, 
Seeing following compilation error on flutter run in redux_app,
`
compiler message: lib/main.dart:25:18: Error: A value of type 'dart.core::List<(#lib1::Store<#lib2::AppState>, dynamic, (dynamic) → void) → void>' can't be assigned to a variable of type 'dart.core::Iterable<(#lib1::Store<#lib3::AppState>, dynamic, (dynamic) → void) → void>'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::Iterable<(#lib1::Store<#lib3::AppState>, dynamic, (dynamic) → void) → void>'.
compiler message:         ..addAll(createAuthMiddleware(context))
compiler message:                  ^
compiler message: lib/main.dart:21:7: Error: A value of type '(#lib1::AppState, dynamic) → #lib1::AppState' can't be assigned to a variable of type '(#lib2::AppState, dynamic) → #lib2::AppState'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '(#lib2::AppState, dynamic) → #lib2::AppState'.
`

Version
`
Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 44b7e7d3f4 (3 weeks ago) • 2018-04-20 01:02:44 -0700
Engine • revision 09d05a3891
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b
`

Thoughts ?

**Comment by ericwindmill** [comment]
@kkganesan It's a Dart 2 error. Dart 2 was released recently. Dart 2 is strongly typed and it's a breaking change. I'm working on cleaning em up.

**Comment by kkganesan** [comment]
@ericwindmill 
with recent pull and flutter upgrade its broken with the same error. 

`
Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 44b7e7d3f4 (6 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b
`
do you have it working locally ?

**Comment by ericwindmill** [comment]
@kkganesan  can you tell me which of the apps you're trying to run?

**Comment by kkganesan** [comment]
its redux_app
https://github.com/ericwindmill/flutter_by_example_apps/tree/master/redux_app

**Comment by ericwindmill** [comment]
@kkganesan the Dart 2 errors are fixed.

**Comment by robert-stevens** [comment]
@ericwindmill 

I cloned the repo yesterday, and found that this error is not fixed. I am getting:

`compiler message: lib/main.dart:21:7: Error: A value of type '(dynamic, dynamic) → #lib1::AppState' can't be assigned to a variable of type '(#lib2::AppState, dynamic) → #lib2::AppState'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '(#lib2::AppState, dynamic) → #lib2::AppState'.
compiler message:       appReducer,
compiler message:       ^
Compiler failed on /Library/WebServer/Documents/flutter/flutter_by_example_apps/redux_app/lib/main.dart`

I also had a compiling error in regards to:

apply plugin: 'com.google.gms.google-services'

It was added in the android/build.gradle instead of the android/app/build.gradle file. (easy fix)

If you could please check these out and let me know.

Thanks.
